name: s2_grid_env
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - geopandas>=0.14
  - dask-geopandas>=0.3.0
  - dask==2024.2.1  # https://github.com/geopandas/dask-geopandas/issues/284
  - pyogrio
  - jupyterlab
